// items-ko-fix.js — DB.items 한글명 보정 + 포챔스에 없는 아이템 제거.
// 출처: 포케모음(pokemoem.com, 포켓몬 챔피언스 한국어 데이터).
// data.js 원본 무수정 원칙 → data.js 로드 후 이 파일을 로드하면 자기적용(패치 + 삭제).
// 재생성: node scripts/build-ko-names.js
window.ITEM_KO_FIX={"Ability Shield":"특성가드","Abomasite":"눈설왕나이트","Absolite":"앱솔나이트","Absolite Z":"앱솔나이트Z","Adamant Crystal":"큰금강옥","Aerodactylite":"프테라나이트","Aggronite":"보스로라나이트","Alakazite":"후디나이트","Altarianite":"파비코리나이트","Ampharosite":"전룡나이트","Audinite":"다부니나이트","Auspicious Armor":"축복받은갑옷","Banettite":"다크펫나이트","Barbaracite":"거북손데스나이트","Baxcalibrite":"드닐레이브나이트","Beedrillite":"독침붕나이트","Black Sludge":"검은오물","Blastoisinite":"거북왕나이트","Blazikenite":"번치코나이트","Booster Energy":"부스트에너지","Cameruptite":"폭타나이트","Chandelurite":"샹델라나이트","Charizardite X":"리자몽나이트X","Charizardite Y":"리자몽나이트Y","Chesnaughtite":"브리가론나이트","Chimechite":"치렁나이트","Clear Amulet":"클리어참","Clefablite":"픽시나이트","Cornerstone Mask":"주춧돌의가면","Covert Cloak":"은밀망토","Crabominite":"모단단게나이트","Darkranite":"다크라이나이트","Delphoxite":"마폭시나이트","Diancite":"디안시나이트","Dragalgite":"드래캄나이트","Dragoninite":"망나뇽나이트","Drampanite":"할비롱나이트","Eelektrossite":"저리더프나이트","Emboarite":"염무왕나이트","Excadrite":"몰드류나이트","Fairy Feather":"요정의깃털","Falinksite":"대여르나이트","Feraligite":"장크로다일나이트","Floettite":"플라엣테나이트","Froslassite":"눈여아나이트","Galladite":"엘레이드나이트","Garchompite":"한카리아스나이트","Garchompite Z":"한카리아스나이트Z","Gardevoirite":"가디안나이트","Gengarite":"팬텀나이트","Glalitite":"얼음귀신나이트","Glimmoranite":"킬라플로르나이트","Golisopite":"갑주무사나이트","Golurkite":"골루그나이트","Greninjite":"개굴닌자나이트","Griseous Core":"큰백금옥","Gyaradosite":"갸라도스나이트","Hawluchanite":"루차불나이트","Hearthflame Mask":"화덕의가면","Heatranite":"히드런나이트","Heracronite":"헤라크로스나이트","Houndoominite":"헬가나이트","Kangaskhanite":"캥카나이트","Latiasite":"라티아스나이트","Latiosite":"라티오스나이트","Leek":"대파","Loaded Dice":"속임수주사위","Lopunnite":"이어롭나이트","Lucarionite":"루카리오나이트","Lucarionite Z":"루카리오나이트Z","Lustrous Globe":"큰백옥","Magearnite":"마기아나이트","Malamarite":"칼라마네로나이트","Malicious Armor":"저주받은갑옷","Manectite":"썬더볼트나이트","Mawilite":"입치트나이트","Medichamite":"요가램나이트","Meganiumite":"메가니움나이트","Meowsticite":"냐오닉스나이트","Metagrossite":"메타그로스나이트","Mewtwonite X":"뮤츠나이트X","Mewtwonite Y":"뮤츠나이트Y","Mirror Herb":"미러허브","Pidgeotite":"피죤투나이트","Pinsirite":"쁘사이저나이트","Punching Glove":"펀치글러브","Pyroarite":"화염레오나이트","Raichunite X":"라이츄나이트X","Raichunite Y":"라이츄나이트Y","Rock Memory":"록메모리","Sablenite":"깜까미나이트","Salamencite":"보만다나이트","Sceptilite":"나무킹나이트","Scizorite":"핫삼나이트","Scolipite":"펜드라나이트","Scovillainite":"스코빌런나이트","Scraftinite":"곤율거니나이트","Sharpedonite":"샤크니아나이트","Skarmorite":"무장조나이트","Slowbronite":"야도란나이트","Staraptite":"찌르호크나이트","Starminite":"아쿠스타나이트","Steelixite":"강철톤나이트","Swampertite":"대짱이나이트","Tatsugirinite":"싸리용나이트","Tyranitarite":"마기라스나이트","Venusaurite":"이상해꽃나이트","Victreebelite":"우츠보트나이트","Wellspring Mask":"우물의가면","Zeraorite":"제라오라나이트","Zygardite":"지가르데나이트"};
window.ITEM_NOT_IN_GAME=["Berry","Berserk Gene","Big Nugget","Bitter Berry","Burnt Berry","Gold Berry","Ice Berry","Mail","Masterpiece Teacup","Mega Stone","Metal Alloy","Mint Berry","Miracle Berry","Mystery Berry","Pink Bow","Polkadot Bow","Pretty Feather","PRZ Cure Berry","PSN Cure Berry","Stick","Strange Ball","Syrupy Apple","Unremarkable Teacup","Vile Vial"];
(function(){if(typeof window==="undefined"||!window.DB)return;var T=window.DB.items;if(!T)return;
for(var _k in window.ITEM_KO_FIX){var _o=T[_k];if(_o===undefined)continue;
if(typeof _o==="string")T[_k]=window.ITEM_KO_FIX[_k];else _o.ko=window.ITEM_KO_FIX[_k];}
for(var _i=0;_i<window.ITEM_NOT_IN_GAME.length;_i++)delete T[window.ITEM_NOT_IN_GAME[_i]];})();
